apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment
  labels:
    app: gol
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gol
  template:
    metadata:
      labels:
        app: gol
    spec:
      containers:
      - name: gol
        image: raajesh404/gol1:latest8
        imagePullPolicy: Always
        ports:
        - containerPort: 8080